language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
script: ./node_modules/.bin/grunt publish
env:
  global:
    secure: wwzLuXpAZC4PyQ3hd095YFkafOMZLm0lqq4UDY3OLUFaNLOnjnNNSjKMP+f5WVRF/sF7LLcFtmx5/BVJIkjCF503yCEQNBu2pYvclI7W2uAknpGzbZx3L43yGTWFUaiSRpvnPh8n3BsSXxE+cnQuVNEIJ5384s3VbR3ClYFC60c=
